# Generated by Django 5.0.3 on 2024-04-05 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='PhoneTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='PhoneProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Изображение')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Слаг')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.phonecategory', verbose_name='Категория')),
                ('tag', models.ManyToManyField(blank=True, related_name='tags', to='product.phonetag', verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Телефоны',
                'verbose_name_plural': 'Телефоны',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='product_pho_name_470775_idx')],
            },
        ),
    ]
