# Generated by Django 5.0.3 on 2024-03-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/static/product/img'),
        ),
    ]
