# Generated by Django 5.0.3 on 2024-03-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_phoneproduct_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneproduct',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='phoneproduct',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=120),
        ),
        migrations.AddIndex(
            model_name='phoneproduct',
            index=models.Index(fields=['name'], name='product_pho_name_470775_idx'),
        ),
    ]
