# Generated by Django 5.0.3 on 2024-03-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_phonecategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecategory',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
