# Generated by Django 5.0.3 on 2024-04-01 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_phonecategory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.phonecategory'),
        ),
        migrations.AddField(
            model_name='phoneproduct',
            name='tag',
            field=models.ManyToManyField(blank=True, to='product.phonetag'),
        ),
    ]
