# Generated by Django 5.0.3 on 2024-04-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_phonetag_alter_phoneproduct_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneproduct',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='product.phonetag'),
        ),
    ]
