# Generated by Django 5.0.3 on 2024-04-01 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_phoneproduct_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonecategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='phoneproduct',
            options={'ordering': ['name'], 'verbose_name': 'Телефоны', 'verbose_name_plural': 'Телефоны'},
        ),
        migrations.AlterModelOptions(
            name='phonetag',
            options={'ordering': ['tag'], 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterField(
            model_name='phonecategory',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='phonecategory',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='phonecategory',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.phonecategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/static/product/img', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='product.phonetag', verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='phonetag',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='phonetag',
            name='tag',
            field=models.CharField(max_length=120, verbose_name='Название'),
        ),
    ]
