# Generated by Django 5.0.3 on 2024-04-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_phonecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Изображение'),
        ),
    ]
