# Generated by Django 5.0.3 on 2024-04-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='/media/profile_photo/default_photo.jpg', null=True, upload_to='media/profile_photo', verbose_name='Image'),
        ),
    ]
